package com.appdev.Jobflex.Entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "job_save")
@Getter
@Setter
public class JobSaveEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private UserEntity user;

    @ManyToOne
    @JoinColumn(name = "job_post_id")
    private JobPostEntity jobPost;

    // JobPost attributes to be stored in JobSaveEntity
    private String title;
    private String company;
    private String location;
    private String pay;
    private String jobType;
    private String shiftAndSchedule;
    private String description;

    // Default constructor
    public JobSaveEntity() {}

    // Constructor for saving job post attributes as well
    public JobSaveEntity(UserEntity user, JobPostEntity jobPost) {
        this.user = user;
        this.jobPost = jobPost;
        this.title = jobPost.getTitle();
        this.company = jobPost.getCompany();
        this.location = jobPost.getLocation();
        this.pay = jobPost.getPay();
        this.jobType = jobPost.getJobType();
        this.shiftAndSchedule = jobPost.getShiftAndSchedule();
        this.description = jobPost.getDescription();
    }

    // Getters and Setters (generated by Lombok)
}
